language: r
r:
  - release
cache: packages
sudo: false

warnings_are_errors: false

r_packages:
  - covr
  - httr
  - jsonlite
  - curl
  - testthat

after_success:
  - Rscript -e 'library(covr); codecov()'

notifications:
  email:
    on_failure: gnehsaijuhz@hotmail.com
