language: r
r:
  - release
cache: packages
sudo: false

r_packages:
  - covr
  - httr
  - jsonlite
  - curl
  - testthat

after_success:
  - Rscript -e 'covr::codecov()'

after_failure:
  - find *Rcheck -name '*.fail' -print -exec cat '{}' \;

notifications:
  email:
    on_failure: robin@kohze.com
