language: r
r:
  - release
cache: packages
sudo: false

warnings_are_errors: false

r_packages:
  - covr
  - httr
  - jsonlite
  - curl
  - testthat

after_success:

  - Rscript \
    --default-packages='httr,curl,testthat,jsonlite' \
    -e 'library(covr); covr::codecov(token="065e3977-f8e1-4ce8-b984-6c1b8de579e6")'

notifications:
  email:
    on_failure: robin@kohze.com
