language: r
r:
  - release
cache: packages
sudo: false

r_packages:
  - covr
  - httr
  - jsonlite
  - curl
  - testthat

after_success:

  - Rscript \
    --default-packages='httr,curl,testthat,jsonlite' \
    -e 'covr::codecov()'

notifications:
  email:
    on_failure: robin@kohze.com
